---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deploy
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
        env: stage
    spec:
      containers:
      - name: whoami
        image: acrdemo5.azurecr.io/whoami:v.0.1.0
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: kama-kama
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8000
    protocol: TCP
  selector:
    app: whoami

